---
name: Example
# date +"%d-%m-%y"
version: "020-20240624-1835"
publisher: 6G-SANDBOX
description: |-
  Sample Appliance for KVM hosts.

  After deploying the appliance, check the status of the deployment in /etc/one-appliance/status. You chan check the appliance logs in /var/log/one-appliance/.
  
  **Note**: Remember to add a password variable in the template in order to have access to it, or make sure that your OpenNebula user has an SSH Public key preconfigured.
  
  **Note**: Remember to update the template in order to add a network after importing it.

short_description: 6G-SANDBOX TNLCM appliance for KVM
tags:
  - ubuntu
  - tnlcm
format: qcow2
# stat -c %W <file>
creation_time: "1719246477"
os-id: Ubuntu
os-release: '22.04'
os-arch: x86_64
hypervisor: KVM
opennebula_version: >-
  6.2, 6.3, 6.4, 6.6, 6.8, 6.10
opennebula_template:
  context:
    network: 'YES'
    set_hostname: "$NAME"
    ssh_public_key: "$USER[SSH_PUBLIC_KEY]"
    jenkins_host: "$JENKINS_HOST"
    jenkins_username: "$JENKINS_USERNAME"
    jenkins_password: "$JENKINS_PASSWORD"
    jenkins_token: "$JENKINS_TOKEN"
    jenkins_job_deploy: "$JENKINS_JOB_DEPLOY"
    jenkins_job_destroy: "$JENKINS_JOB_DESTROY"
    ansible_vault: "$ANSIBLE_VAULT"
    mail_username: "tnlcm.uma@gmail.com"
    mail_password: "czrs rsdg ktpm rrlx"
  cpu: '2'
  vcpu: '2'
  cpu_model:
    model: "host-passthrough"
  graphics:
    listen: 0.0.0.0
    type: vnc
  hot_resize:
    cpu_hot_add_enabled: 'YES'
    memory_hot_add_enabled: 'YES'
  hypervisor: kvm
  memory: '4096'
  memory_unit_cost: 'MB'
  os:
    arch: x86_64
  logo: images/logos/tnlcm.png
  lxd_security_privileged: 'true'
  user_inputs:
    jenkins_host: "M|text|JENKINS_HOST: IP address of the Jenkins server used to deploy the Trial Networks| |127.0.0.1"
    jenkins_username: "M|text|JENKINS_USERNAME: Username used to login into the Jenkins server to access and retrieve pipeline info. | |tnlcm"
    jenkins_password: "M|text|JENKINS_PASSWORD: Password used to login into the Jenkins server to access and retrieve pipeline info. | |tnlcm"
    jenkins_token: "M|text|JENKINS_TOKEN: Token to authenticate while sending POST requests to the Jenkins Server API| |114803bbd81a27f5eb9052ce4d3b9212d4"
    jenkins_job_deploy: "M|text|JENKINS_JOB_DEPLOY: Name of the Jenkins pipeline used to deploy Trial Networks| |TN_DEPLOY"
    jenkins_job_destroy: "M|text|JENKINS_JOB_DESTROY: Name of the Jenkins pipeline used to destroy Trial Networks| |TN_DESTROY"
    ansible_vault: "M|text|ANSIBLE_VAULT: Password used to decrypt the contents of the 6G-Sandbox-Sites repository file| |"
logo: tnlcm.png
images:
  - name: TNLCM_6GSandbox
    url: >-
      https://rawimages.mobilesandbox.cloud:9443/tnlcm020.qcow2
    type: OS
    dev_prefix: vd
    driver: qcow2
    # qemu-img info <file> | awk '/virtual size:/ {print $5}' | sed 's/[^0-9]*//g'
    size: "7516192768"
    checksum:
      # md5sum <file> | cut -d' ' -f1
      md5: "85971d547fe036800fd1832fc1f13d2d"
      # sha256sum <file> | cut -d' ' -f1
      sha256: "c5457a1cd3f8e8a2efc2e9429960dc0e8874d1f538ed0aca4f79a102fd2a28ba"
