version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-proxy/certs:/etc/nginx/certs:ro
    ports:
      - "443:443"
    extra_hosts:
      - register:host-gateway
      - nginx:host-gateway
      - host.docker.internal:host-gateway
      - vault:host-gateway
    restart: unless-stopped

networks:
  default:
    name: capif-network
    external: true